services:

  eventhubexplorer:
    image: dvlaskin/eventhubexplorer:0.2.0
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    ports:
      - "5235:8080"
    volumes:
      - data-volume:/app/Data
    networks:
      - docker-network
        
volumes:
  data-volume:
    
networks:
  docker-network:
    external: true
        
  