services:

  eventhubexplorer:
    image: eventhubexplorer
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    ports:
      - "5235:8080"
    volumes:
      - data-volume:/app/Data
        
volumes:
  data-volume:
        
  